- .travis.yml
I updated Travis to test using new py3 images from Docker Hub.
> Travis py3

- python/om_adflow.py
The PetscKSP linear solver was renamed to PETScKrylov with OpenMDAO v3.x. This PR addresses this modification. Currently, if someone has OpenMDAO v3.x installed, they won't be able to import ADflow due to this depreciated name. This PR just fixes the name, and we can import ADflow regularly. I did not test any OpenMDAO functionality because we will phase out the current om_adflow wrapper anyways (see issue #50). This change does not affect any of the regular ADflow code, and I think the only case that used the PetscKSP solver was some work in @JustinSGray's thesis. This PR closes #39.
- Bugfix (non-breaking change which fixes an issue)
> update for openmdao v3.x api change for petscksp 

- .gitignore
- python/inputFiles/Readme.md
- src/adjoint/ADFirstAidKit/debugAD.f
- src/adjoint/ADFirstAidKit/dpStack.c
- src/adjoint/initPETScWrap.c
- src/build/fort_depend.py
- src/initFlow/variableReading.F90
- src/inputParam/inputParamRoutines.F90
- src/metis-4.0/metis.c
- src/output/writeCGNSSurface.F90
- src/overset/oversetUtilities.F90
- src/overset/stringOps.F90
- src/overset/zipperMesh.F90
- src/preprocessing/preprocessingAPI.F90
- src/warping/getForces.F90
Updated the code to remove the compiler warnings
Updated gitignore for the input files
Fixed a few use only statements where we had both a bare import and specific imports
Improved syntax of the input file instructions
- Bugfix (non-breaking change which fixes an issue)
- Code style update (formatting, renaming)
> Warnings fix

- doc/install.rst
Clarifying how to run reg tests. It took me a while to figure out I had to follow the instructions in the inputFiles Readme.md because nothing happened and there was no diff when I tried to run the tests.
- Documentation update
- Checked the GitHub "rich diff" for the .rst
> Clarifying how to run reg tests

- adflow/pyADflow.py
- doc/conf.py
- doc/pyADflow.rst
Updated path for autodoc so the API can be rendered properly
- Documentation update
> Updated docs

- .travis.yml
- doc/install.rst
- inputFiles/Readme.md
- inputFiles/get-input-files.sh
I updated the links to the regression files, and added a new shell script for extracting everything.
- Maintenance
> Updated link and docs for regression input files

- setup.py
For workshop issue "Remove overly restrictive dependency versions"
> Remove overly restrictive dependency versions

- doc/install.rst
See title
- Documentation update
> Fixed broken link to 3rd party packages in docs

- tests/reg_tests/test_adjoint.py
on centos the value differs by greater than the tolerance, but we have decided that it doesn't differ significantly enough to be considered wrong. thus we need to adjust the tolerance.
> adjusted tolerance for cmplx test

- .travis.yml
- tests/reg_tests/reg_test_classes.py
- tests/reg_tests/reg_test_utils.py
- tests/reg_tests/test_2D_conv_nozzle.py
- tests/reg_tests/test_adjoint.py
- tests/reg_tests/test_cl_solve.py
- tests/reg_tests/test_conic_conv_nozzle.py
- tests/reg_tests/test_functionals.py
- tests/reg_tests/test_solve.py
- tests/reg_tests/test_time_accurate_naca0012.py
After some confusion with testflo, it turns out `-n` specifies the number of tests to run concurrently. Therefore, I am setting it to `1` for Travis. I am also changing the `N_PROCS` parameter to 2 since it's not really necessary to run MPI tests with 4 procs, and this would ensure some sort of consistency between Travis and the build bot.
> Updated nprocs for tests

- doc/conf.py
- doc/requirements.txt
- doc/tutorial.rst
I updated docs to use the organization-wide setup.
> Update docs configuration

- doc/performance.rst
I added a reference to Kenway2019a, which includes a strong scaling study.
> Added strong scaling reference to docs

- setup.py
This PR does two things:
- Added `extras_require` for testing dependencies (closes #88)
- Removed hard-coded `long_description` in favour of directly reading the contents of the README file. This is the recommended approach I believe.
N/A
> Added `extras_require` for testing

- doc/tutorial.rst
Adding basic information on kill signals that ADflow support and some basic usage.
> Adding information on kill signals

- inputFiles/get-input-files.sh
This PR updates the bash script `get-input-files.sh` so that it can be run from any directory, and still extract the files to the right location. This is done by first extracting the directory containing the bash script itself, then prepending all paths with that.
I have tested this locally, and running it both from the root directory and the `input_files` directory yield the desired outcome.
> Updated bash script

- adflow/pyADflow.py
- setup.py
Closes #108. 
This PR fixes the docstrings and now uses the `printOptions` functions.
> Change to `printOptions` and fix docstrings

- .gitignore
- doc/install.rst
Removing and changing `inputFiles` to `input_files`. Also minor updates to `.gitignore`.
> Removing inputFiles from .gitignore and docs

- doc/options.yaml
As far as I can tell, there is no automatic check for the lift direction and no way to leave `liftIndex` unspecified. I removed these lines from the docs.
> Updated liftIndex docs

- doc/solvers.rst
Small typo fix. Not sure if we use pull requests for things this small or just tack onto something else.
NA
> Fixed typo in solver docs

- tests/reg_tests/test_adjoint.py
Function names in pygeo changed due to [this issue](https://github.com/mdolab/pygeo/issues/33) in [this PR](https://github.com/mdolab/pygeo/pull/91), causing example scripts and tests in other repos to change as well. 
Example scripts should run with no warnings on newest pygeo when changes are merged
> Update pygeo function calls

- config/defaults/config.LINUX_GFORTRAN.mk
- config/defaults/config.LINUX_INTEL.mk
- config/defaults/config.LINUX_INTEL_SAFE.mk
- config/defaults/config.OSX_GFORTRAN.mk
Updates the compilers wrappers used. Now the more modern fortran mpi compiler wrapper mpifort used instead of the mpif90, see [here](open-mpi.org/faq/?category=mpi-apps#mpifort-vs-mpif77-and-mpif90) for GNU and similarly for Intel mpiifort, see [here](software.intel.com/content/www/us/en/develop/documentation/mpi-developer-reference-linux/top/command-reference/compiler-commands.html)
Tested on `c7-intel-impi-latest` and `u20-gcc-ompi-latest`
> Updating config files to use the more modern wrappers

- .github/azure-pipelines.yaml
- .github/build_complex.sh
- .github/build_real.sh
- .github/test_complex.sh
- .github/test_real.sh
- README.md
> Added coverage reporting

- adflow/__init__.py
- adflow/mphys/mphys_adflow.py
- adflow/oversetCheck.py
- adflow/pyADflow.py
- adflow/pyADflow_C.py
- adflow/pyDynamicPerformance.py
- adflow/pyPerformanceClass.py
- adflow/pyWeightAndBalance.py
- adflow/pyWingCG.py
- setup.py
- src/f2py/pyf_preprocessor.py
- tests/reg_tests/reg_test_classes.py
- tests/reg_tests/test_2D_conv_nozzle.py
- tests/reg_tests/test_actuator.py
- tests/reg_tests/test_adjoint.py
- tests/reg_tests/test_cavitation.py
- tests/reg_tests/test_center_of_force.py
- tests/reg_tests/test_cl_solve.py
- tests/reg_tests/test_conic_conv_nozzle.py
- tests/reg_tests/test_jacVecProdBWDFast.py
- tests/reg_tests/test_jacVecProdFWD.py
- tests/reg_tests/test_overset.py
- tests/reg_tests/test_solve.py
- tests/reg_tests/test_solver_combos.py
- tests/reg_tests/test_time_accurate_naca0012.py
- tests/reg_tests/test_time_spectral_naca64A010.py
ADflow doesn't currently work with any numpy past 1.21 (#256 ), this PR reflects this in the installation requirements
1 hour
> Fix numpy dependency and do black reformatting

- .git-blame-ignore-revs
I added the fprettify commit hash to .git-blame-ignore-revs so that it does not show up when you git blame. I also changed the black formatting commits to the squashed commit so it actually works.
2 days
> Updated git blame ignore

- tests/reg_tests/test_adjoint.py
> Fix added DVs for complex rotating wing test

- adflow/mphys/mphys_adflow.py
Failed solutions in the MPhys wrapper currently all use the same `baseName`. If you are doing multipoint and have separate analyses whose solutions fail, they will overwrite each other. For example, the first cruise analysis failure file would be called "analysis_fail_000_surf.plt". If a top of climb case later fails, it will write a file with the same name, overwriting the cruise failure.
This PR adds the `AeroProblem` name to the failed solution file name, so instead of "analysis_fail_000_surf.plt", it would be "cruise_analysis_fail_000_surf.plt". This fixes the overwriting problem.
A day
> Add AeroProblem name to analysis failure solution filenames

- adflow/__init__.py
There have been significant changes to ADflow since the last release, but I believe the changes constitute a minor release.
> bump minor version

- doc/introduction.rst
Some of the students in class were getting into ADflow and had some questions. This update to the intro should help a little. 
Now we explicitly mention the finite volume discretization, and point towards `options` and `solvers` pages.
No rush
> The introduction docs in ADflow need some updating

- config/defaults/config.LINUX_INTEL.mk
- config/defaults/config.LINUX_INTEL_AVX2.mk
Same as https://github.com/mdolab/pyhyp/pull/87
1 day
> Update intel config files to work with new compilers

- input_files/get-input-files.sh
This PR updates the link to download the input files for tests. 
Using the current link fails with the message shown below.
```
Connecting to umich.edu (umich.edu)|172.66.0.37|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2025-05-06 07:10:08 ERROR 403: Forbidden.
```
When tests pass
> Update link for input files

- doc/options.yaml
I had some updates to the options docs from a while ago that I never merged:
- Referenced the journal version of my preconditioning paper instead of the conference paper
- Fixed a couple of errors for the ANK and NK solvers
Not urgent
> Update preconditioning paper reference and fix some typos in options docs
