mdolab/adflow

- src/warping/getForces.F90
this is a branch we don't normally use, one of the manually differentiated routines had a bug. This fix seems to check out on a simple tests case
> fixed bug in non-tractionforce derivatives

- src/NKSolver/NKSolvers.F90
- src/NKSolver/blockette.F90
- src/adjoint/masterRoutines.F90
All of the issues explained above is with the option useblockettes:True, which is the default. Regular, non-blockette residual routines do not have these issues.
As mentioned in issue #36, some intermediate variables that are computed during the residual computation are not copied back to main memory when blockettes are used. This may cause issues when reverse AD routines are called with outdated intermediate variables. This PR modifies the blockette code so that when `updateIntermed` flag is `True`, the blockette residual routine updates all the intermediate variables that are needed by the reverse AD routines. The PR also modifies how `blocketteRes` is called from the NKSolver module so that after an ANK or NK step, the intermediate variables are always up to date.
This does not cause …
> Copy intermediate variables from blockette memory

- tests/reg_tests/test_adjoint.py
Apparently when the other parameters were changed it changed the test results just slightly.
Loosening the tolerance a little more should fix the failed builds.
```
AssertionError: 
Not equal to tolerance rtol=5e-09, atol=1e-10
Failed value for: mach_mdo_tutorial
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 3.97857608e-10
Max relative difference: 6.86584997e-09
x: array(0.057947)
y: array(0.057947)
```
> updated tol because buildbot is failing.

- adflow/pyADflow.py
`self.adflow.updategamma()` doesn't exist. It should be `self.adflow.flowutils.updategamma()`
ADflow doesn't crash anymore when setting a custom gamma value.
> fix call updategamma()

- adflow/pyADflow.py
This PR fixes a minor logic in applying displacement files. Now, even if the point sets are up to date, if the displacements are nonzero they are still applied. I also made minor adjustments to the docstrings.
N/A
> Updated displacement file handling

- adflow/om_func_comp.py
- adflow/pyADflow.py
In the OpenMDAO wrapper, the adjoint gradients get divided by the number of procs used. To test it, i ran some gradient computations on a N0012 grid with only alpha as DesignVar:
Type | #Procs | Gradient cd vs alpha | gradient * #Procs
-- | -- | -- | --
Adjoint | 36 | 2.69E-05 | 0.000967035
Adjont | 12 | 8.06E-05 | 0.000967035
Adjoint | 2 | 0.00048352 | 0.00096704
Adjoint | 1 | 0.00096703 | 0.00096703
FD | 36 | 0.00096705 |  
FD | 12 | 0.00096711 |  
FD | 2 | 0.00096705 |  
FD | 1 | 0.00096705 |  
I tested it with the same N0021 setup, but i added the smalest FFD-Box possible to also verify shape variables:
Type | #Procs | Step | Gradient cd vs alpha | Gradient Shape vs alpha |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- …
> Fixed OpenMDAO wrapper adjoint gradients.

- adflow/__init__.py
- adflow/pyADflow.py
- setup.py
With recent addition of self.comm to BaseSolver in baseclasses (see mdolab/baseclasses#29) self.comm will is overwritten.
However, PR mdolab/baseclasses#30 now adds self.comm as an argument to BaseSolver making it clear to the user where self.comm is set and less error-prone.
This PR adjusts the code to the above changes.
> self.comm is now set in BaseSolver

- adflow/pyADflow.py
This is a minor change to setOption where casting to lower happens _after_ calling `super().setOption`. This ensures that the options set in baseclasses have the correct capitalization, e.g. for `printModifiedOptions`.
All existing tests pass.
> Minor change to setOption

- adflow/pyADflow.py
Previously, the modified options were printed on every `__call__`, which is excessive. Now, they are printed only when switching aero problems, since it's possible for a solver to use different options based on aero problems.
This works locally.
> Only print modified options when switching ap

- input_files/get-input-files.sh
- tests/reg_tests/test_2D_conv_nozzle.py
- tests/reg_tests/test_adjoint.py
- tests/reg_tests/test_cl_solve.py
- tests/reg_tests/test_conic_conv_nozzle.py
- tests/reg_tests/test_functionals.py
- tests/reg_tests/test_solve.py
- tests/reg_tests/test_time_accurate_naca0012.py
- tests/unit_tests/test_basics.py
Closes #122 . I uploaded on `mfile` a new `tar.gz` folder without subfolders, and changed the download bash script to untar directly into `input_files`. All the tests have been updated to point to this folder.
Note: the new `tar.gz` also includes a new `.cgns` file used for the rotating frame adjoint test added with #121 
The tests have been checked locally.
- [NA] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
> Input file fix

- .github/test_complex.sh
- .github/test_real.sh
This PR adjusts the testing scripts so that different `-n` values can be used depending on whether it's on Azure or the build bot.
> Added conditional for nprocs

- config/defaults/config.LINUX_GFORTRAN.mk
- config/defaults/config.LINUX_INTEL.mk
- config/defaults/config.LINUX_INTEL_SAFE.mk
- config/defaults/config.OSX_GFORTRAN.mk
- src/build/Makefile
- src/modules/su_cgns.F90
- src_cs/build/Makefile
This PR removes support for the old CGNS 3.2.1 library. The code will now only support a proper fortran module. Related to this we are updating our `latest` testing images to use CGNS 4.1.2. Once merged our images test for versions 3.3.0 and 4.1.2. Users still on 3.2.1 will thus need to upgrade.
Testing was performed both locally and on `u20-gcc-ompi-latest`.
> Removing CGNS support for versions older than 3.3.0

- adflow/MExt.py
- adflow/checkZipper.py
- adflow/oversetCheck.py
- adflow/pyADflow.py
- adflow/pyADflow_C.py
Previously `MExt` used to raise a lot of resource warnings regarding unclosed files. This PR fixes it by switching from `imp` to `importlib` since the former is deprecated. I also made some other minor adjustments to the code to improve readability/code quality.
Code that runs ADflow will not receive `ResourceWarning` anymore.
> Fixed MExt

- doc/tutorial.rst
- src/partitioning/readCGNSGrid.F90
As Sandy explained today, the mesh unit conversion factor was originally in SUmb, but ADflow should only be used with meshes in meters. I updated the mesh unit warning and also added a line in the docs.
> Updated mesh unit warning

- adflow/pyADflow.py
This PR adds numbering to `failed_mesh.cgns` so that multiple failed meshes can be written out without overwriting the previous one.
I verified this on Great Lakes and it works as expected.
> Number the failed mesh output

- src/adjoint/adjointUtils.F90
@sseraj and I figured out that PETSc 3.15 somehow messes with the KSP monitor, and turns on a monitor when we have more than one global preconditioner iteration. As we never monitored that before, and the code is currently printing a bunch of zeros, we opted to remove it. 
Closes #154  , and additionally fixes a bug for complexified ADflow. Running complex NK with `nkouterpreconits` >1 leads to a type error in the monitor printout and an instant failure of the run. No monitor, no issue!
I tested both ADflow and pyAerostructure runs and I see no issue, but please verify that this small fix does not remove any relevant monitor feature.
set `nkouterpreconits:2` and verify how this fix removes the extra `KSP` residual printouts
> removed extra ksp monitor when outerpreconits > 1

- tests/reg_tests/test_adjoint.py
The `complex` keyword argument has been renamed to `isComplex` in pyGeo. This PR makes the corresponding updates here. I also renamed a few other things to make the code more readable.
Existing tests should run and no longer raise a warning.
> Fix complex kwarg

- src/output/tecplotIO.F90
- src/overset/oversetUtilities.F90
- src/preprocessing/preprocessingAPI.F90
- src/utils/haloExchange.F90
Um, I think all the lift files written in the last however many years have all had this typo... how did this never come up before?
> Fixed typo

- src/adjoint/adjointDebug.F90
Added a compiler directive to  prevent optimization of the `printADSeed` subroutine added in the last PR
time the compile time with and without the directive. 
Or look at the compile times in the azure tests
> fixed long compile time on intel compiler

- adflow/pyADflow.py
- src/inputParam/inputParamRoutines.F90
- src/modules/ADjointPETSc.F90
- src/preprocessing/preprocessingAPI.F90
- src/utils/utils.F90
If ADflow has an issue in its __init__ it will often try to deallocate variables that haven't been allocated yet. This will usually obscure the original error.  This was particularly annoying for me since I was working on pyAeroProblem, which is used before the preprocessing has been complete.
To solve this I added lots of if (allocated(blah)) statements to prevent it from deallocating variables that don't exist yet. 
Before
```
python test_basics.py
#
#
#
-> Alpha... 0.000000 
E[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see …
```
> added lots of if allocated statements

- src/adjoint/adjointAPI.F90
- src/adjoint/adjointUtils.F90
- src/bcdata/BCData.F90
- src/output/outputMod.F90
- src/output/tecplotIO.F90
- src/overset/oversetUtilities.F90
- src/overset/stringOps.F90
- src/overset/zipperMesh.F90
- src/partitioning/gridChecking.F90
- src/preprocessing/preprocessingAPI.F90
- src/solver/actuatorRegion.F90
- src/solver/solvers.F90
- src/utils/utils.F90
- src/wallDistance/wallDistance.F90
I changed a lot of the printing that used the format `e.` to use `es.`, so that numbers show up as `4.9E2` instead of `0.49E3`. I was really annoyed with the constant leading zero, so this should make everything more readable.
I used some regex to find these, so I might've missed some stuff. Would appreciate some checking by ADflow maintainers since I'm not as familiar with the code. This may also be a good time to change other printing formats, especially since I noticed we are now showing 16 decimal places which is probably too much.
I ran the MACH-Aero tutorial and saw that the printing is now using proper scientific notation.
> Changed printing to use proper scientific notation

- src/f2py/adflow.pyf
- src/modules/monitor.f90
- src/output/writeCGNSVolume.F90
- src/solver/solvers.F90
This PR fixes a regression that happened a long time ago. The solver convergence history is now written properly to the CGNS volume file.
Run any case with `writevolumesolution = True`. Load the resulting CGNS file into Tecplot and,
1. specify "Advanced Options"
2. choose to "Load global convergence history data" when opening
3. check that XY line plot produces the desired output, by setting the appropriate mapping.
> Convergence history is now written to the CGNS volume file

- adflow/pyADflow.py
- src/f2py/adflow.pyf
- src/modules/inputParam.F90
I implemented the restartAdjoint option, which previously did nothing. The default behavior, which is to use the previous adjoint solution as the initial guess, is unchanged.
Using `"restartAdjoint": False` improved my optimization convergence slightly. I don't know if this will be helpful in general, but it's a nice option to have even if it is just for debugging.
> Implemented restartAdjoint option

- adflow/pyADflow.py
- doc/options.yaml
- src/f2py/adflow.pyf
- src/modules/inputParam.F90
- src/modules/monitor.f90
- src/solver/solvers.F90
This is another solver dev/debugging tool.
It makes it easy to print the solution after every major iterations to identify patterns in the converged states and residuals.
add the option `writeSolutionEachIter` to a runscript.
> Option to write solution files after every major iteration

- src/overset/stringOps.F90
- tests/reg_tests/test_zipper.py
This fixes the zipper mesh segfault issue first reported by @awccopp. 
When creating the zipper mesh, indexing out of bounds can occur when the number of closest points we are searching for is greater than the total number of points on a string. Capping the initial `nSearch` in the `stringMatch` routine solves the issue.
The current initial value for `nSearch` is 50, which explains why the problem only appears on small meshes like @awccopp's airfoil cases. I added a test with a simple overset cube mesh that can reproduce the error.
Regular urgency; one week
Run test_zipper.py without compiling the fix. The result will be a segfault (or 'index outside of expected range' if compiled with a bounds check flag).
Run the test again after recompiling. The test should now pass.
> Zipper mesh segfault fix

- README.md
- src/initFlow/initializeFlow.F90
- tests/unit_tests/test_restart.py
This PR addresses issue #199 
This would only effect cases were a solution file is being read by a case with split blocks (blocks are split for load balancing).
This did not show up in our tests because our test meshes have lots of blocks and we test with only 2 procs so there is no need to split any blocks.
There was a change in behavior from CGNS 3.4 onward that affects how partial ranges of data are read from a CGNS file. 
Specifically, instead of using the range given, the rind cells are now added to the range. See [here for src with comment highlighting change](https://github.com/CGNS/CGNS/blob/55afcfec8a0c9503dfead89c3cec477283e4fc5a/src/cgns_internals.c#L9488-L9500)
But we were already doing this on the adflow level so it happened twice resulting in an invalid range. 
The fix is …
> Read solution fix for split blocks

- adflow/pyADflow.py
Closes #191. I was thinking about actually listing out the possible choices for this option, but a quick glance at the Fortran code shows that this may be a bit complicated to do. Maybe the current description is okay.
Should be pretty quick.
None
> Switched MGCycle to sg by default

- src/solver/surfaceIntegrations.F90
When you call `getSolution` with multiple families the values calculated by the earlier families are zeroed on the last iteration. 
I don't believe this was ever the intended behavior and frankly I'm surprised this was left on unfixed for so long.
When using `evalFunctions` 'getSolution` is called individually for each group which is why this isn't currently messing up everyone's cases
1 week 
Ask @lambe for his test script if you'd like
> Quick bug fix in getSolution

- config/compilerCheck.sh
- src/build/Makefile
This PR adds a script that checks the compiler version and injects the `-fallow-argument-mismatch` flag if it detects GCC version 10 and newer.  For more detail on the issue, see #243.
No rush
Test compiling adflow with GCC 10+ either locally or in a container.
> Allow GCC 10+ to compile

- src_cs/build/Makefile
This PR adds the `-fallow-argument-mismatch` flag to the complex build if it detects GCC version 10 and newer. This is equivalent to what was done in #244.
Should be quick.
- [] Bugfix (non-breaking change which fixes an issue)
Test compiling adflow with GCC 10+ either locally or in a container using the complex build.
> Adding flag on complex build to support gcc 10 

- setup.py
- src/f2py/adflow.pyf
numpy 1.22 introduced some changes to how array dimensions are determined with f2py. From what I can tell, `intent(out)` strings of undetermined length are no longer valid (or have never been valid but did not previously raise an error).
ADflow has 4 string variables with `intent(inout)` that cause problems with numpy 1.22. I posted the error message in #256. However, we never use these variables in Python after passing them to Fortran, so I changed them to `intent(in)`. This fixes the error and does not change the behavior of the code.
1 week
I installed numpy 1.22, recompiled ADflow with these changes, and checked that all tests pass.
> Fixed f2py string intent

- adflow/pyADflow.py
- doc/conf.py
- doc/install.rst
- doc/requirements.txt
- setup.py
Closes #205
I ignored the dependencies in the dynamic stability files because they are unused and do not work. I opened a separate issue (#268) to remove or refactor those files.
1 week
> Updated dependencies in setup.py

- adflow/pyADflow.py
- doc/options.yaml
- src/f2py/adflow.pyf
- src/modules/inputParam.F90
- src/preprocessing/preprocessingAPI.F90
I added an option to turn off printing of the negative volume indices and coordinates. The printout is useful for debugging, but I find that it mainly pollutes the output during production runs.
Setting the option `printNegativeVolumes` to False will mean that messages like the following will not be printed:
```
#
#
#
#--------------------------------------------------------------------
#
.
.
.
```
The `returnFail` error message will still be printed, so it is still clear that negative volumes have been encountered:
```
#
#--------------------------- !!! Error !!! ----------------------------
#* returnFail called by processor 0
#* Run-time error in procedure metric
#* Error message: Negative volumes present in grid.
#*
#---------------------------------------------------------------------- …
```
> Added option to turn off negative volume print out

- src/NKSolver/blockette.F90
The blockette code had a bug when transferring face velocities to the blockette data. This code is not used for steady state, non rotating meshes. I am not sure if this was the reason rotating cases were not working with blockettes or we ignored some other terms as well. 
Instant-merge
> Bug fix in blockette code from 2019

- adflow/__init__.py
- adflow/mphys/mphys_adflow.py
Closes #293 
Adds a collection of functions that are then used by all ADflow MPhys components to set various mesh coordinates and states in the solver from the input and output vectors passed in by OpenMDAO. Previously, several of these inputs were not being used which was leading to incorrect derivatives when multiple aerostructural scenarios used the same `ADflowBuilder`.
1 week
I have been testing these changes on a modified version of the [mach tutorial wing aerostructural example](https://github.com/OpenMDAO/mphys/tree/main/examples/aerostructural/mach_tutorial_wing/adflow_meld_tacs) from the mphys repo:
```
-----------------
Total Derivatives
-----------------
+-----------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of …
```
> Overhaul the setting of OpenMDAO inputs and outputs in MPhys wrapper

- adflow/pyADflow.py
- doc/options.yaml
In the existing version, the output file numbering is hard coded to be three digits long (e.g. 003). If there are more than 999 output files, the number is extended to four digits. This messes with file sorting in some cases because the 1001th case can come between the 101st and 102nd, depending on the sorting algorithm.
This PR adds a new option, `writeSolutionDigits`, to manually specify the number of digits in the output filename to get around this sorting problem.
A few days
Run a case that writes out solution files. Try changing the `writeSolutionDigits` option to something other than the default of 3 and observe that the output filenames change.
> Option to specify number of leading zeros in solution filename number

- config/defaults/config.LINUX_INTEL.mk
- config/defaults/config.LINUX_INTEL_AVX2.mk
See https://github.com/mdolab/pysurf/pull/31 for details
> Make Intel config compiler check more robust

- config/defaults/config.LINUX_INTEL.mk
- config/defaults/config.LINUX_INTEL_AVX2.mk
Inline comment messes with the `ifdef` check, see https://github.com/mdolab/pyhyp/pull/87#issuecomment-2115027287 for details
> Fix icc check
